// layouts/post.vue
<template>
<div>
  <header class="intro-header" style="background-image: url('/images/bg1920x872.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>{{ title }}</h1>
          <!-- <span class="meta"> Written on {{ page.date | date: "%B %e, %Y" }}</span> -->
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <nuxt/>
      </div>
    </div>

    <hr>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
       <!--comment-->
      </div>
    </div>
  </div>
</article>
</div>
</template>

<script>
export default {
  async asyncData ({ app }) {
    return {
      title: ''
    }
  },
  layout: 'default'
}
</script>

<style>

</style>

// client/imports/app/post/post.component.ts
import { Component, OnInit } from '@angular/core';
import template from './post.component.html';

@Component({
  selector: 'app-post',
  template
})
export class PostComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
<app-header [bgUrl]="post.bgImageUrl || 'images/PostDefault.jpg'" [heading]="post.title" [meta]="post.createdAt | date:'yyyy/MM/dd'" ></app-header>
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1" [innerHTML]="post.content | markdown">
      </div>
    </div>
  </div>
</article>
<hr>
